Fix/yml2dag list
starlake-ai/starlake pull request #487
Opened 2023-04-19 12:19 UTC by tiboun

__Feature__:
- allow to change date and timestamp format during data extraction

__Bug fix__:
- list command for internal ressources doesn't work for yml2dag
- **Breaking Change** Make default configuration of CSV writer in extract-data to match default value of Metadata.
- keep original args in starlake.sh  when they have spaces

2023-04-19 12:48 UTC, hayssams requested changes

2023-04-19 12:48 UTC, hayssams commented on src/main/scala/ai/starlake/extract/SLResultSetHelperService.scala
> +        value = ""
Should we replace this line with  value = handleObject(rs.getObject(colIndex))

2023-04-19 20:06 UTC, tiboun commented on src/main/scala/ai/starlake/extract/SLResultSetHelperService.scala
> +        value = ""
Done according to what you suggested :)

2023-04-20 06:13 UTC, hayssams approved these changes
LGTM

2023-04-20 07:00 UTC, merged