WIP: Handle automatically merge instructions in transforms
starlake-ai/starlake pull request #557
Opened 2023-06-28 21:30 UTC by hayssams

## Summary
A clear and concise description of the overall goals of the pull request's commits.

**Related Issue: #IssueId**

**PR Type: Bug Fix | Feature | Documentation**

**Status: WIP/Ready to review**

**Breaking change? Yes/No**

## Description
### Solution
Describe your changes in detail

### How has this been tested?
Outline the steps taken to test the PR (unit tests? Integration tests? tested impacts on other project features? ...)

### Other changes
Describe any other additional work done:
bug fixes, tweaks, small refactors

### Deploy Notes
Notes regarding deployment of the contained body of work. These should note any
new dependencies, new scripts, new environment variables, ...

### Remaining Todos
This should be done before merging this PR:
* [ ] - Task1
* [ ] - Task2

## Contributor checklist:
Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!
- [ ] My code follows the code style of this project.
- [ ] I have updated the Release notes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-06-29 12:48 UTC, tiboun requested changes
Great PR, the beginning of a new user experience is coming in auto jobs

2023-06-29 12:48 UTC, tiboun commented on src/main/scala/ai/starlake/job/sink/bigquery/BigQueryJobBase.scala
> +  def tableExists(datasetName: String, tableName: String)(implicit settings: Settings): Boolean = {
we may split getOrCreateTable into two function `getTable` and `createTable`, define getOrCreateTable with those two and use the getTable in order to define this method, what do you think ?

2023-06-29 12:48 UTC, tiboun commented on src/main/scala/ai/starlake/job/transform/AutoTask.scala
> +    taskDesc.database
In `BigQueryFreshnessInfo`, `AutoTask.createBigQueryConfig`, `resolveTableRefInDomainsAndJobs`, `ingestionWorkflow`,  we may use this getDatabase in order to have only one way of resolving it, what do you think?

Furthermore, why do we have a database attribute in the task and another one in the sink ? Maybe we should keep one of them only.

2023-06-29 12:48 UTC, tiboun commented on src/main/scala/ai/starlake/job/transform/AutoTask.scala
> +    val tableExists = bqNativeJob("ignore sql").tableExists(taskDesc.domain, taskDesc.table)
Do we move getOrCreateTable/datasets and tableExists to the companion object and have the ability to use them outside of it without instantiating a fake job ?

2023-06-29 12:48 UTC, tiboun commented on src/main/scala/ai/starlake/utils/SQLUtils.scala
> +  def extractColumnNames(sql: String): List[String] = {
Does jSqlParser infer * select or not ?

```
with
  my_table as (select col1, col2, col3),
  my_table2 as (select col1, col4)
  select my_table.* except(col2), myTable2.col4 from my_table inner join my_table2 using(col1)
```

expected output is col1, col3, col4.

2023-06-29 12:48 UTC, tiboun commented on src/main/scala/ai/starlake/utils/SQLUtils.scala
> +           |${buildWhenNotMatchedInsert(sql)}
We've got the ability to define `when not matched by source` as well. This allows, for instance, to delete entries in target table.

2023-06-29 12:48 UTC, tiboun commented on src/main/scala/ai/starlake/utils/SQLUtils.scala
> +           |${buildWhenMatchedUpdate(sql)}
We are forcing users to follow this way of merge request. Do we plan to give the user the ability to override the different merge with templates ? I think we must provide this.

2023-06-29 12:48 UTC, tiboun commented on src/main/scala/ai/starlake/utils/SQLUtils.scala
> +           |
merge clauses are not limited, we may have many WHEN MATCHED clause.
The only restriction to merge statement is to have one source line matching at MOST 1 merge clause if I remember well. That is why we can add other check along with the MATCHED clause. Example [here](https://cloud.google.com/bigquery/docs/reference/standard-sql/dml-syntax#merge_statement).

2023-06-30 12:29 UTC, hayssams commented on src/main/scala/ai/starlake/job/transform/AutoTask.scala
> +    val tableExists = bqNativeJob("ignore sql").tableExists(taskDesc.domain, taskDesc.table)
We need to pass it the cliConfig. That's why it's not an object.

2023-06-30 12:29 UTC, hayssams commented on src/main/scala/ai/starlake/job/transform/AutoTask.scala
> +    taskDesc.database
About the database field, I agree with you, I guess I need to discuss this one.

2023-06-30 12:29 UTC, hayssams commented on src/main/scala/ai/starlake/job/transform/AutoTask.scala
> +    taskDesc.database
They all rely on the same function, I you look at the code.

2023-06-30 12:30 UTC, hayssams commented on src/main/scala/ai/starlake/job/sink/bigquery/BigQueryJobBase.scala
> +  def tableExists(datasetName: String, tableName: String)(implicit settings: Settings): Boolean = {
It make sens but I am not able to come up with a clean split.

2023-07-01 13:49 UTC, merged

2023-07-01 14:38 UTC, hayssams commented on src/main/scala/ai/starlake/job/sink/bigquery/BigQueryJobBase.scala
> +  def tableExists(datasetName: String, tableName: String)(implicit settings: Settings): Boolean = {
Done

2023-07-01 14:39 UTC, hayssams commented on src/main/scala/ai/starlake/job/transform/AutoTask.scala
> +    taskDesc.database
We worked on it together and I cleaned it up