take into account optional cron within datasets
starlake-ai/starlake pull request #883
Opened 2024-05-17 16:14 UTC by fupelaqu

## Summary
A clear and concise description of the overall goals of the pull request's commits.

**Related Issue: #IssueId**

**PR Type: Bug Fix | Feature | Documentation**

**Status: WIP/Ready to review**

**Breaking change? Yes/No**

## Description
### Solution
Describe your changes in detail

### How has this been tested?
Outline the steps taken to test the PR (unit tests? Integration tests? tested impacts on other project features? ...)

### Other changes
Describe any other additional work done:
bug fixes, tweaks, small refactors

### Deploy Notes
Notes regarding deployment of the contained body of work. These should note any
new dependencies, new scripts, new environment variables, ...

### Remaining Todos
This should be done before merging this PR:
* [ ] - Task1
* [ ] - Task2

## Contributor checklist:
Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!
- [ ] My code follows the code style of this project.
- [ ] I have updated the Release notes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-05-22 16:14 UTC, mhdkassir approved these changes
Lgtm

2024-05-24 16:52 UTC, zedach commented on src/main/python/starlake-airflow/ai/starlake/airflow/gcp/starlake_airflow_cloud_run_job.py
> +        self.cloud_run_async_poke_interval = float(__class__.get_context_var('cloud_run_async_poke_interval', "30", self.options)) if not cloud_run_async_poke_interval else cloud_run_async_poke_inter
this changes seems to be related to cloud run jobs feature, I'm I wrong ?

2024-05-24 16:52 UTC, zedach commented on src/main/python/starlake-airflow/ai/starlake/airflow/gcp/starlake_airflow_cloud_run_job.py
> +                    f"--async --region {self.cloud_run_job_region} --project {self.project_id} --format='get(metadata.name)'" #--task-timeout 300
also Here. is this related to optional cron within dataset ?

2024-05-24 16:52 UTC, zedach commented on src/main/python/starlake-airflow/ai/starlake/airflow/gcp/starlake_airflow_dataproc_job.py
> +        cluster_name = f"{self.cluster_config.dataproc_name}-{cluster_id.replace('_', '-')}-{TODAY}"[0:51] if not cluster_name else cluster_name[0:51]
Same here in this file: change seems not to be related to the feature but with dataproc cluster name limitation. maybe should be in a fix PR, what do you think ?

2024-05-24 16:52 UTC, zedach commented on src/main/resources/templates/dags/__common_airflow.py.j2
> +    return dt.fromtimestamp(dt.now().timestamp())
Why not using `dt.now()`  directly to obtain the datetime object ?

2024-05-24 16:52 UTC, zedach commented on src/main/resources/templates/dags/__common_airflow.py.j2
> +from urllib import parse
maybe import quote directly simplify the code 
`from urllib.parse import quote`

2024-05-24 17:39 UTC, zedach requested changes
LGTM. Some changes are due to formatting and other corrections that don't seem to be related to the new functionality. I propose to include them in another PR if that's the case

2024-05-24 17:57 UTC, zedach approved these changes

2024-05-25 05:03 UTC, fupelaqu commented on src/main/python/starlake-airflow/ai/starlake/airflow/gcp/starlake_airflow_cloud_run_job.py
> +        self.cloud_run_async_poke_interval = float(__class__.get_context_var('cloud_run_async_poke_interval', "30", self.options)) if not cloud_run_async_poke_interval else cloud_run_async_poke_inter
it is right but it has been added in this PR while testing the latter

2024-05-25 05:07 UTC, fupelaqu commented on src/main/python/starlake-airflow/ai/starlake/airflow/gcp/starlake_airflow_dataproc_job.py
> +        cluster_name = f"{self.cluster_config.dataproc_name}-{cluster_id.replace('_', '-')}-{TODAY}"[0:51] if not cluster_name else cluster_name[0:51]
You are totally right this update is related with dataproc cluster nae limitation and has been added in this PR while testing the latter. I don't think we should create a specific PR for this

2024-05-28 10:17 UTC, merged